#!/usr/bin/env Rscript
options(warn=2);options(stringsAsFactors=FALSE)
args<-commandArgs(trailingOnly=TRUE);repo<-if(length(args))normalizePath(args[[1L]],winslash="/",mustWork=TRUE)else normalizePath(getwd(),winslash="/",mustWork=TRUE)
source(file.path(repo,"framework/R/TDABMUserRadiusContract.R"));source(file.path(repo,"framework/R/TDABMRadiusDiagnostics.R"))
mk<-function(radius,automatic=FALSE,optimality="NONE",sha=paste(rep("a",64),collapse=""),approved_by="tester",approved_at="2026-08-08T12:00:00+01:00",lo=0.8,hi=1.2)tdabm_urc_contract(application="synthetic",target_radius=radius,selection_basis="substantively_interpretable_fixed",interpretation=paste(rep("This synthetic contract records an interpretable explicit user radius decision.",3),collapse=" "),decision_rationale=paste(rep("The user may choose a radius outside diagnostic anchors when the recorded substantive rationale supports it.",3),collapse=" "),topology_axes=c("x","y"),scaling="none",metric="euclidean",precision_policy="substantive_rounding",pipeline_reference_radius=1,pipeline_reference_method="non-binding majority cover transition reference",review_band_lower=lo,review_band_upper=hi,diagnostic_audit_sha256=sha,approved_by=approved_by,approved_at=approved_at,automatic_selection_performed=automatic,optimality_claim=optimality)
inside<-mk(1);below<-mk(0.6);above<-mk(1.5)
stopifnot(all(tdabm_urc_validate(inside)$pass),all(tdabm_urc_validate(below)$pass),all(tdabm_urc_validate(above)$pass))
stopifnot(identical(inside$review_band_position,"INSIDE_REVIEW_BAND"),identical(below$review_band_position,"BELOW_REVIEW_BAND"),identical(above$review_band_position,"ABOVE_REVIEW_BAND"))
stopifnot(!all(tdabm_urc_validate(mk(1,automatic=TRUE))$pass))
stopifnot(!all(tdabm_urc_validate(mk(1,optimality="OPTIMAL"))$pass))
stopifnot(!all(tdabm_urc_validate(mk(1,sha=""))$pass))
stopifnot(!all(tdabm_urc_validate(mk(1,approved_by=""))$pass))
stopifnot(!all(tdabm_urc_validate(mk(1,approved_at=""))$pass))
stopifnot(!all(tdabm_urc_validate(mk(1,lo=1.2,hi=0.8))$pass))
s<-data.frame(radius=1.5,one_ball_rate=1,median_n_balls=1,median_effective_n_balls=1,median_max_ball_share_observations=0.90,mean_pairwise_cover_jaccard=1,connected_rate=1,no_isolate_rate=1)
ref<-data.frame(reference_radius=1,review_band_lower=0.8,review_band_upper=1.2)
review<-tdabm_rd_user_radius_review(s,1.5,ref,2)
tech<-tdabm_rd_technical_user_radius_review(s,review,0.75)
stopifnot(isTRUE(tech$technical_evidence_complete),identical(tech$status,"TECHNICAL_EVIDENCE_COMPLETE_USER_DECISION_EXTERNAL"),identical(tech$user_approval_status,"EXPLICIT_USER_DECISION_REQUIRED"),all(tech$diagnostic_flags$blocking==FALSE))
stopifnot(tech$diagnostic_flags$triggered[tech$diagnostic_flags$diagnostic=="outside_resolution_review_band"])
stopifnot(tech$diagnostic_flags$triggered[tech$diagnostic_flags$diagnostic=="severe_dominance_marker_crossed"])
stopifnot(tech$diagnostic_flags$triggered[tech$diagnostic_flags$diagnostic=="median_ball_count_at_or_below_one"])
stopifnot(tech$diagnostic_flags$triggered[tech$diagnostic_flags$diagnostic=="median_effective_ball_count_at_or_below_one"])
bad<-s;bad$mean_pairwise_cover_jaccard<-NA_real_;stopifnot(!tdabm_rd_technical_user_radius_review(bad,review)$technical_evidence_complete)
bad<-s;bad$radius<-1.4;stopifnot(!tdabm_rd_technical_user_radius_review(bad,review)$technical_evidence_complete)
cat("PASS: explicitly approved radii below, inside and above the review band all form valid contracts.\n")
cat("PASS: review-band position is retained as diagnostic evidence without becoming an admissibility gate.\n")
cat("PASS: severe dominance, one-ball and low effective-resolution states remain non-blocking diagnostic warnings.\n")
cat("PASS: genuine malformed/non-finite and exact-radius-mismatch evidence still fails closed.\n")
cat("PASS: user approval remains external to technical diagnostics; automatic approval is FALSE and optimality claim is NONE.\n")
