#!/usr/bin/env Rscript
options(warn=2);options(stringsAsFactors=FALSE)
args<-commandArgs(trailingOnly=TRUE);repo<-if(length(args))normalizePath(args[[1L]],winslash="/",mustWork=TRUE)else normalizePath(getwd(),winslash="/",mustWork=TRUE)
source(file.path(repo,"framework/R/TDABMUserRadiusContract.R"));source(file.path(repo,"framework/R/TDABMTopologyFreeze.R"));source(file.path(repo,"framework/R/TDABMFrozenTopology.R"))
mkc<-function(radius,automatic=FALSE,optimality="NONE",sha=paste(rep("a",64),collapse=""),approved_by="tester",approved_at="2026-08-08")tdabm_urc_contract(application="synthetic",target_radius=radius,selection_basis="substantively_interpretable_fixed",interpretation=paste(rep("interpretable radius contract with explicit user approval",4),collapse=" "),decision_rationale=paste(rep("user decision follows but is not determined by topology diagnostics",4),collapse=" "),topology_axes=c("x","y"),scaling="none",metric="euclidean",precision_policy="substantive_rounding",pipeline_reference_radius=0.97,pipeline_reference_method="non-binding majority cover transition",review_band_lower=0.8,review_band_upper=1.2,diagnostic_audit_sha256=sha,approved_by=approved_by,approved_at=approved_at,automatic_selection_performed=automatic,optimality_claim=optimality)
inside<-mkc(1);below<-mkc(0.6);above<-mkc(1.5)
stopifnot(all(tdabm_urc_validate(inside)$pass),all(tdabm_urc_validate(below)$pass),all(tdabm_urc_validate(above)$pass))
stopifnot(identical(inside$review_band_position,"INSIDE_REVIEW_BAND"),identical(below$review_band_position,"BELOW_REVIEW_BAND"),identical(above$review_band_position,"ABOVE_REVIEW_BAND"))
stopifnot(!all(tdabm_urc_validate(mkc(1,automatic=TRUE))$pass),!all(tdabm_urc_validate(mkc(1,optimality="OPTIMAL"))$pass),!all(tdabm_urc_validate(mkc(1,sha=""))$pass),!all(tdabm_urc_validate(mkc(1,approved_by=""))$pass),!all(tdabm_urc_validate(mkc(1,approved_at=""))$pass))
cat("PASS: generic user-radius contract permits explicit approval below, inside or above the non-binding review band.\n")
cat("PASS: automatic selection, forbidden optimality claims and missing provenance/approval fields fail closed.\n")
d<-data.frame(id=c("b","a","c"),x=c(2,0,4),y=c(0,0,0));a<-tdabm_tf_canonicalize(d,"id",c("x","y"));b<-tdabm_tf_canonicalize(d[c(3,1,2),],"id",c("x","y"));stopifnot(identical(a$ids,b$ids),identical(as.matrix(a$axes),as.matrix(b$axes)));cat("PASS: canonical point preparation is row-order invariant.\n")
tdabm_tf_compile_cpp(file.path(repo,"framework/BallMapper.cpp"))
raw_probe<-SimplifiedBallMapperCppInterface(a$axes,data.frame(interface_value=rep(1,nrow(a$axes))),2.1)
stopifnot(as.integer(raw_probe$landmarks[[1L]])==0L)
stopifnot(identical(tdabm_tf_cpp_landmarks_one_based(raw_probe$landmarks,nrow(a$axes)),as.integer(raw_probe$landmarks)+1L))
bm<-tdabm_tf_build(a$axes,2.1);stopifnot(all(tdabm_tf_validate_object(bm,3,2.1)$pass));stopifnot(all(as.integer(bm$landmarks)>=1L),identical(bm$tdabm_landmark_index_contract,"R_ONE_BASED_NORMALIZED_FROM_CPP_ZERO_BASED"));cat("PASS: raw C++ zero-based landmark positions are normalized once to the R one-based canonical point order.\n")
r1<-tdabm_ft_recolour(bm,c(1,2,3));r2<-tdabm_ft_recolour(bm,c(9,4,0));stopifnot(tdabm_ft_topology_identical(bm,r1$object),tdabm_ft_topology_identical(bm,r2$object));cat("PASS: arbitrary recolouring preserves the frozen topology exactly.\n")
badbm<-bm; bad_idx<-as.integer(badbm$points_covered_by_landmarks[[1L]]); if(length(bad_idx)>1L) bad_idx<-bad_idx[-length(bad_idx)] else bad_idx<-c(bad_idx, setdiff(seq_len(nrow(a$axes)),bad_idx)[1L]); badbm$points_covered_by_landmarks[[1L]]<-bad_idx; stopifnot(!identical(tdabm_tf_topology_lines(bm,a$ids),tdabm_tf_topology_lines(badbm,a$ids)));cat("PASS: topology fingerprint representation detects membership changes.\n")
cat("PASS: P1.4-C generic topology-freeze contract test complete.\n")
