root <- normalizePath(file.path(dirname(sub("^--file=", "", commandArgs(trailingOnly=FALSE)[grep("^--file=", commandArgs(trailingOnly=FALSE))][1])), ".."), mustWork=TRUE)
source(file.path(root,"R","functions.R"))
food_root <- normalizePath(file.path(root,".."), mustWork=TRUE)
cands <- c(
  file.path(food_root,"01_source_reconstruction","data_staged","hfa_f0f1_baseline.csv"),
  Sys.glob(file.path(food_root,"FoodDeserts_HFA_F0F1_Source_Reconstruction_*","data_staged","hfa_f0f1_baseline.csv"))
)
cands <- unique(cands[file.exists(cands)])
assert(length(cands)>0, "Could not locate F0/F1 baseline under %s. Keep the successful F0/F1 directory beside this F2 directory.", food_root)
base_path <- tail(cands,1)
msg("Using F0/F1 baseline: ", base_path)
b <- read_csv_flex(base_path)
assert(nrow(b)==33755, "F0/F1 baseline row count %d != 33755", nrow(b))
assert(length(unique(b$lsoa21cd))==33755, "F0/F1 baseline LSOA21 codes are not unique")
out <- file.path(root,"data_staged","f0f1_baseline_inherited.csv")
dir.create(dirname(out),recursive=TRUE,showWarnings=FALSE)
file.copy(base_path,out,overwrite=TRUE)
meta <- data.frame(source_path=base_path, rows=nrow(b), unique_lsoa21=length(unique(b$lsoa21cd)), sha256=sha256_file(base_path))
write_csv(meta,file.path(root,"results","f2","f0f1_inheritance.csv"))
cat("F0F1_INHERITANCE_OK rows=33755\n")
